/**
 * Replace with API-mapped rows when wiring the dashboard.
 * Shape: { id, name, icon, accent, accentSoft, total, approvalRate, investigated, verified, approved, rejected }
 */
export const PROGRAM_APPLICATION_CARD_DUMMY_DATA = [
  {
    id: 'ration',
    name: 'Ration Program',
    icon: 'bag',
    accent: '#16a34a',
    accentSoft: '#dcfce7',
    total: 1245,
    approvalRate: 71.5,
    investigated: 180,
    verified: 720,
    approved: 890,
    rejected: 210,
  },
  {
    id: 'community',
    name: 'Community Services',
    icon: 'users',
    accent: '#7c3aed',
    accentSoft: '#ede9fe',
    total: 980,
    approvalRate: 66.3,
    investigated: 140,
    verified: 510,
    approved: 650,
    rejected: 150,
  },
  {
    id: 'financial',
    name: 'Financial Assistance',
    icon: 'heart',
    accent: '#ea580c',
    accentSoft: '#ffedd5',
    total: 760,
    approvalRate: 68.4,
    investigated: 95,
    verified: 410,
    approved: 520,
    rejected: 120,
  },
  {
    id: 'education',
    name: 'Education',
    icon: 'book',
    accent: '#2563eb',
    accentSoft: '#dbeafe',
    total: 1100,
    approvalRate: 74.5,
    investigated: 165,
    verified: 680,
    approved: 820,
    rejected: 180,
  },
  {
    id: 'water',
    name: 'Water & Sanitation',
    icon: 'droplet',
    accent: '#0891b2',
    accentSoft: '#cffafe',
    total: 640,
    approvalRate: 65.6,
    investigated: 88,
    verified: 340,
    approved: 420,
    rejected: 90,
  },
  {
    id: 'kasb',
    name: 'KASB Program',
    icon: 'tool',
    accent: '#4f46e5',
    accentSoft: '#e0e7ff',
    total: 430,
    approvalRate: 69.8,
    investigated: 62,
    verified: 245,
    approved: 300,
    rejected: 60,
  },
  {
    id: 'sewing',
    name: 'Livelihood / Sewing',
    icon: 'tool',
    accent: '#0d9488',
    accentSoft: '#ccfbf1',
    total: 310,
    approvalRate: 72.0,
    investigated: 48,
    verified: 180,
    approved: 223,
    rejected: 45,
  },
  {
    id: 'tree',
    name: 'Green Initiative',
    icon: 'bag',
    accent: '#15803d',
    accentSoft: '#dcfce7',
    total: 520,
    approvalRate: 70.2,
    investigated: 72,
    verified: 300,
    approved: 365,
    rejected: 78,
  },
  {
    id: 'wheelchair',
    name: 'Mobility Support',
    icon: 'heart',
    accent: '#be123c',
    accentSoft: '#ffe4e6',
    total: 198,
    approvalRate: 64.1,
    investigated: 28,
    verified: 95,
    approved: 127,
    rejected: 38,
  },
  {
    id: 'area_ration',
    name: 'Area Ration',
    icon: 'shopping',
    accent: '#ca8a04',
    accentSoft: '#fef9c3',
    total: 875,
    approvalRate: 67.9,
    investigated: 118,
    verified: 480,
    approved: 594,
    rejected: 132,
  },
];
