/**
 * Registry of CSV import templates per backend entity_name.
 * Add new modules here when a handler is registered in data_import service.
 */
export const ENTITY_IMPORT_CONFIG = {
  donors: {
    label: 'Donors',
    templateFilename: 'donors-import-template',
    description:
      'Import individual or CSR donors. Required: donor_type, email, phone, name. For csr also include organization_name (or organization_id).',
    headers: [
      'donor_type',
      'email',
      'phone',
      'name',
      'first_name',
      'last_name',
      'cnic',
      'organization_name',
      'organization_id',
      'organization_registration',
      'organization_email',
      'organization_phone',
      'organization_address',
      'affiliation_role',
      'address',
      'city',
      'country',
      'postal_code',
      'source',
      'notes',
      'is_active',
      'notification_subscription',
      'recurring',
      'multi_time_donor',
      'assigned_to_user_id',
      'referrer_user_id',
      'password',
    ],
    sampleRow: {
      donor_type: 'individual',
      email: 'donor@example.com',
      phone: '03001234567',
      name: 'Sample Donor',
      first_name: 'Sample',
      last_name: 'Donor',
      city: 'Lahore',
      country: 'Pakistan',
      source: 'import',
      is_active: 'true',
      notification_subscription: 'true',
      recurring: 'false',
      multi_time_donor: 'false',
    },
  },
  donation_box: {
    label: 'Donation Boxes',
    templateFilename: 'donation-box-import-template',
    description:
      'Import physical donation boxes. Required: shop_name and city (city_id or city_name). Route, key_no, and box_id_no are optional. Duplicates = same shop_name + shopkeeper + phone (same shop name alone is allowed).',
    headers: [
      'shop_name',
      'route_id',
      'route_name',
      'city_id',
      'city_name',
      'box_id_no',
      'key_no',
      'shopkeeper',
      'cell_no',
      'landmark_marketplace',
      'box_type',
      'status',
      'frequency',
      'active_since',
      'notes',
      'assigned_user_ids',
    ],
    sampleRow: {
      shop_name: 'Sample General Store',
      route_id: '',
      city_id: '1',
      box_id_no: '',
      key_no: '',
      shopkeeper: 'Ahmed Khan',
      cell_no: '03001234567',
      landmark_marketplace: 'Main Bazaar',
      box_type: 'medium',
      status: 'active',
      frequency: 'weekly',
      active_since: new Date().toISOString().split('T')[0],
      notes: 'Imported via CSV',
      assigned_user_ids: '',
    },
  },
  donation_box_donations: {
    label: 'Donation Box Collections',
    templateFilename: 'donation-box-collections-import-template',
    description:
      'Import collection records. Required: collection_amount, collection_date. Identify the box with donation_box_id, key_no, or shop_name.',
    headers: [
      'donation_box_id',
      'key_no',
      'shop_name',
      'collection_amount',
      'collection_date',
      'collector_name',
      'collected_by_id',
      'payment_method',
      'status',
      'receipt_number',
      'notes',
    ],
    sampleRow: {
      donation_box_id: '',
      key_no: 'KEY-001',
      shop_name: '',
      collection_amount: '1500',
      collection_date: new Date().toISOString().split('T')[0],
      collector_name: 'Field Officer',
      collected_by_id: '',
      payment_method: 'cash',
      status: 'pending',
      receipt_number: '',
      notes: 'Imported via CSV',
    },
  },
  volunteers: {
    label: 'Volunteers',
    templateFilename: 'volunteers-import-template',
    description:
      'Import volunteers. Required: name, phone. Optional: email, skills, interest_areas (comma/semicolon separated), status, verification_status, etc.',
    headers: [
      'name',
      'phone',
      'email',
      'cnic',
      'date_of_birth',
      'gender',
      'city',
      'area',
      'availability',
      'availability_days',
      'hours_per_week',
      'willing_to_travel',
      'skills',
      'interest_areas',
      'category',
      'motivation',
      'emergency_contact_name',
      'emergency_contact_phone',
      'emergency_contact_relation',
      'status',
      'assigned_department',
      'interview_required',
      'verification_status',
      'source',
      'comments',
    ],
    sampleRow: {
      name: 'Ali Hassan',
      phone: '03001234567',
      email: 'ali.hassan@example.com',
      cnic: '35202-1234567-1',
      date_of_birth: '1995-06-15',
      gender: 'male',
      city: 'Lahore',
      area: 'Gulberg',
      availability: 'weekends',
      availability_days: 'Saturday;Sunday',
      hours_per_week: '8',
      willing_to_travel: 'true',
      skills: 'Event management;Fundraising',
      interest_areas: 'Education;Health',
      category: 'general',
      motivation: 'Want to give back to community',
      emergency_contact_name: 'Sara Hassan',
      emergency_contact_phone: '03009876543',
      emergency_contact_relation: 'sister',
      status: 'pending',
      assigned_department: '',
      interview_required: 'false',
      verification_status: 'unverified',
      source: 'import',
      comments: 'Imported via CSV',
    },
  },
  users: {
    label: 'Users',
    templateFilename: 'users-import-template',
    description:
      'Import ERP users. Required: first_name, last_name, email, department, role. Optional password defaults to ChangeMe@123. Department/role must match system enum values (e.g. fund_raising, user).',
    headers: [
      'first_name',
      'last_name',
      'email',
      'department',
      'role',
      'password',
      'phone',
      'user_code',
      'dob',
      'address',
      'cnic',
      'gender',
      'joining_date',
      'emergency_contact',
      'blood_group',
      'isActive',
      'manager_id',
    ],
    sampleRow: {
      first_name: 'Sample',
      last_name: 'User',
      email: 'sample.user@example.com',
      department: 'fund_raising',
      role: 'user',
      password: 'ChangeMe@123',
      phone: '03001234567',
      gender: 'male',
      blood_group: 'B+',
      isActive: 'true',
    },
  },
};

export const getImportConfig = (entityName) => {
  const key = String(entityName || '').trim().toLowerCase();
  return ENTITY_IMPORT_CONFIG[key] || null;
};
