/**
 * Registry of CSV import templates per backend entity_name.
 * Add new modules here when a handler is registered in data_import service.
 */
export const ENTITY_IMPORT_CONFIG = {
  donors: {
    label: 'Donors',
    templateFilename: 'donors-import-template',
    description:
      'Import individual or CSR donors. Required: donor_type, email, phone. For individual rows include name; for csr include company_name and contact_person.',
    headers: [
      'donor_type',
      'email',
      'phone',
      'name',
      'first_name',
      'last_name',
      'cnic',
      'company_name',
      'company_registration',
      'contact_person',
      'designation',
      'company_address',
      'company_phone',
      'company_email',
      'address',
      'city',
      'country',
      'postal_code',
      'source',
      'notes',
      'is_active',
      'notification_subscription',
      'recurring',
      'multi_time_donor',
      'assigned_to_user_id',
      'referrer_user_id',
      'password',
    ],
    sampleRow: {
      donor_type: 'individual',
      email: 'donor@example.com',
      phone: '03001234567',
      name: 'Sample Donor',
      first_name: 'Sample',
      last_name: 'Donor',
      city: 'Lahore',
      country: 'Pakistan',
      source: 'import',
      is_active: 'true',
      notification_subscription: 'true',
      recurring: 'false',
      multi_time_donor: 'false',
    },
  },
  donation_box: {
    label: 'Donation Boxes',
    templateFilename: 'donation-box-import-template',
    requiresYear: true,
    description:
      'Import physical donation boxes. Required: shop_name + Route + City. Enter Active Since year in the dialog — sheet month (e.g. Dec / 12) becomes the 1st of that month. FRD Officer Reference matches a user by name (not stored). Missing routes are created for that city.',
    headers: [
      'box_id_no',
      'key_no',
      'region',
      'city_name',
      'frd_officer_reference',
      'shop_name',
      'shopkeeper',
      'cell_no',
      'address',
      'google_coordinates',
      'landmark_marketplace',
      'route',
      'box_type',
      'active_since',
      'status',
    ],
    sampleRow: {
      box_id_no: 'FSD-L-141',
      key_no: '355',
      region: 'Lahore',
      city_name: 'Faisalabad',
      frd_officer_reference: 'Imran Ashraf',
      shop_name: 'Jamia Tul Hussnain',
      shopkeeper: 'Ashiq sb',
      cell_no: '0331-6665036',
      address: 'Green Town Millat Road FSD',
      google_coordinates: 'F37W+WRX Faisalabad',
      landmark_marketplace: 'Green Town',
      route: '16',
      box_type: 'large',
      active_since: 'December',
      status: 'active',
    },
  },
  donation_box_donations: {
    label: 'Donation Box Collections',
    templateFilename: 'donation-box-collections-import-template',
    description:
      'Import collection records. Required: collection_amount, collection_date. Identify the box with donation_box_id, key_no, or shop_name.',
    headers: [
      'donation_box_id',
      'key_no',
      'shop_name',
      'collection_amount',
      'collection_date',
      'collector_name',
      'collected_by_id',
      'payment_method',
      'status',
      'receipt_number',
      'notes',
    ],
    sampleRow: {
      donation_box_id: '',
      key_no: 'KEY-001',
      shop_name: '',
      collection_amount: '1500',
      collection_date: new Date().toISOString().split('T')[0],
      collector_name: 'Field Officer',
      collected_by_id: '',
      payment_method: 'cash',
      status: 'pending',
      receipt_number: '',
      notes: 'Imported via CSV',
    },
  },
  volunteers: {
    label: 'Volunteers',
    templateFilename: 'volunteers-import-template',
    description:
      'Import volunteers. Required: name, phone. Optional: email, skills, interest_areas (comma/semicolon separated), status, verification_status, etc.',
    headers: [
      'name',
      'phone',
      'email',
      'cnic',
      'date_of_birth',
      'gender',
      'city',
      'area',
      'availability',
      'availability_days',
      'hours_per_week',
      'willing_to_travel',
      'skills',
      'interest_areas',
      'category',
      'motivation',
      'emergency_contact_name',
      'emergency_contact_phone',
      'emergency_contact_relation',
      'status',
      'assigned_department',
      'interview_required',
      'verification_status',
      'source',
      'comments',
    ],
    sampleRow: {
      name: 'Ali Hassan',
      phone: '03001234567',
      email: 'ali.hassan@example.com',
      cnic: '35202-1234567-1',
      date_of_birth: '1995-06-15',
      gender: 'male',
      city: 'Lahore',
      area: 'Gulberg',
      availability: 'weekends',
      availability_days: 'Saturday;Sunday',
      hours_per_week: '8',
      willing_to_travel: 'true',
      skills: 'Event management;Fundraising',
      interest_areas: 'Education;Health',
      category: 'general',
      motivation: 'Want to give back to community',
      emergency_contact_name: 'Sara Hassan',
      emergency_contact_phone: '03009876543',
      emergency_contact_relation: 'sister',
      status: 'pending',
      assigned_department: '',
      interview_required: 'false',
      verification_status: 'unverified',
      source: 'import',
      comments: 'Imported via CSV',
    },
  },
  users: {
    label: 'Users',
    templateFilename: 'users-import-template',
    description:
      'Import ERP users. Required: first_name, last_name, email, department, role. Optional password defaults to ChangeMe@123. Department/role must match system enum values (e.g. fund_raising, user).',
    headers: [
      'first_name',
      'last_name',
      'email',
      'department',
      'role',
      'password',
      'phone',
      'user_code',
      'dob',
      'address',
      'cnic',
      'gender',
      'joining_date',
      'emergency_contact',
      'blood_group',
      'isActive',
      'manager_id',
    ],
    sampleRow: {
      first_name: 'Sample',
      last_name: 'User',
      email: 'sample.user@example.com',
      department: 'fund_raising',
      role: 'user',
      password: 'ChangeMe@123',
      phone: '03001234567',
      gender: 'male',
      blood_group: 'B+',
      isActive: 'true',
    },
  },
};

export const getImportConfig = (entityName) => {
  const key = String(entityName || '').trim().toLowerCase();
  return ENTITY_IMPORT_CONFIG[key] || null;
};
